name: Unit testing application

on:
    push:
        branches: [master]
    create:
        tags: '*'

jobs:
    test:
        name: unit testing app on ${{matrix.node_version}}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: ['12.16']
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: |
                  npm ci
                  npm run build --if-present
                  npm test
            - name: Archive test coverage
              uses: actions/upload-artifact@v2
              with:
                  name: code-coverage-report
                  path: coverage/index.html
